export const notSuitableOptions = [
  "People over 70 years",
  "People over 95 years",
  "People with altitude sickness",
  "Babies under 1 year",
  "Children under 10 years",
  "Children under 11 years",
  "Children under 12 years",
  "Children under 13 years",
  "Children under 14 years",
  "Children under 15 years",
  "Children under 16 years",
  "Children under 18 years",
  "Children under 2 years",
  "Children under 3 years",
  "Children under 4 years",
  "Children under 5 years",
  "Children under 6 years",
  "Children under 7 years",
  "Children under 8 years",
  "Children under 3 ft (90 cm)",
  "Children under 9 years",
  "Cruise ship guests",
  "People with diabetes",
  "Divers without certification",
  "People diving up to 24 hours prior",
  "Drivers under 18 years",
  "Drivers under 21 years",
  "Drivers under 16 years",
  "Hearing-impaired people",
  "People with high blood pressure",
  "People with lactose intolerance",
  "People with low level of fitness",
  "Non-swimmers",
  "People with nut allergies",
  "People over 287 lbs (130 kg)",
  "People over 309 lbs (140 kg)",
  "People over 209 lbs (95 kg)",
  "People afraid of heights",
  "People over 220 lbs (100 kg)",
  "People over 243 lbs (110 kg)",
  "People over 254 lbs (115 kg)",
  "People over 260 lbs (118 kg)",
  "People over 275 lbs (125 kg)",
  "People over 297 lbs (135 kg)",
  "People over 331 lbs (150 kg)",
  "People over 5 ft 9 in (180 cm)",
  "People over 6 ft 6 in (200 cm)",
  "People over 200 lbs (91 kg)",
  "People over 230 lbs (104 kg)",
  "People over 250 lbs (113 kg)",
  "People over 264 lbs (120 kg)",
  "People over 270 lbs (122 kg)",
  "People over 280 lbs (127 kg)",
  "People over 300 lbs (136 kg)",
  "People over 350 lbs (159 kg)",
  "People over 55 years",
  "People over 60 years",
  "People over 65 years",
  "People over 75 years",
  "People prone to seasickness",
  "People under 3 ft 3 in (100 cm)",
  "People under 3 ft 6 in (110 cm)",
  "People under 3 ft 9 in (120 cm)",
  "People under 4 ft 3 in (130 cm)",
  "People under 4 ft 4 in (135 cm)",
  "People under 4 ft 6 in (140 cm)",
  "People under 4 ft 8 in (145 cm)",
  "People under 4 ft 9 in (150 cm)",
  "People under 5 ft 1 in (155 cm)",
  "People under 5 ft 2 in (160 cm)",
  "People under 17 years",
  "People under 19 years",
  "Children under 44 lbs (20 kg)",
  "People under 20 years",
  "People under 21 years",
  "People under 66 lbs (30 kg)",
  "People under 77 lbs (35 kg)",
  "People under 88 lbs (40 kg)",
  "People under 99 lbs (45 kg)",
  "Children under 50 lbs (23 kg)",
  "People who can't drive manual transmission",
  "People who can't ride a bike",
  "People with a cold",
  "People with animal allergies",
  "People with back problems",
  "People with claustrophobia",
  "People with epilepsy",
  "People with food allergies",
  "People with gluten intolerance",
  "People with haemophilia",
  "People with heart problems",
  "People with insect allergies",
  "People with kidney problems",
  "People with mobility impairments",
  "People with motion sickness",
  "People without driver’s license",
  "People without experience",
  "People with recent surgeries",
  "People with respiratory issues",
  "People with vertigo",
  "People with pre-existing medical conditions",
  "Pregnant women",
  "People over 80 years",
  "Children under 33 lbs (15 kg)",
  "Vegans",
  "Vegetarians",
  "Visually impaired people",
  "Wheelchair users",
];

export const notAllowedOptions = [
  "Alcohol and drugs",
  "Audio recording",
  "Baby carriages",
  "Baby strollers",
  "Bachelor & bachelorette party groups",
  "Party groups",
  "Backpacks",
  "Bags",
  "Bare feet",
  "Bikes",
  "Boots",
  "Bright colors",
  "Cameras",
  "Cellphones",
  "Chewing gum",
  "Climbing",
  "Cooler",
  "Crutches",
  "Diving",
  "Handcarts",
  "Alcoholic drinks in the vehicle",
  "Drinks in the vehicle",
  "Drinks",
  "Drones",
  "Food in the vehicle",
  "Electric wheelchairs",
  "Electronic devices",
  "Explosive substances",
  "Feeding animals",
  "Firework",
  "Fishing",
  "Flashlight",
  "Flash photography",
  "Food",
  "Food and drinks",
  "Food and drinks in the vehicle",
  "Glass objects",
  "Hats",
  "Headphones",
  "High-heeled shoes",
  "Shoes indoors",
  "Insect repellent",
  "Intoxication",
  "Jeans",
  "Jewelry",
  "Jumping",
  "Littering",
  "Luggage or large bags",
  "Making fire",
  "Making noise",
  "Military-style clothing",
  "Mobility scooters",
  "Loose clothing",
  "Non-folding strollers",
  "Non-folding wheelchairs",
  "Waterproof cameras",
  "Nudity",
  "Open-toed shoes",
  "Oversize luggage",
  "Padlocks",
  "Pets",
  "Pets (assistance dogs allowed)",
  "Photography inside",
  "Plastic bags",
  "Plastic bottles",
  "Professional cameras",
  "Red wine",
  "Riding the animals",
  "Ripped clothing",
  "Sandals or flip flops",
  "Scooter",
  "See-through clothing",
  "Selfie sticks",
  "Shoes",
  "Shorts",
  "Short skirts",
  "Skateboards",
  "Skates",
  "Skirts",
  "Sleeveless shirts",
  "Slippers",
  "Smoking",
  "Smoking indoors",
  "Smoking in the vehicle",
  "Snorkeling",
  "Speakers",
  "Sports shoes",
  "Sportswear",
  "Sprays or Aerosols",
  "Strong fragrances",
  "Sunglasses",
  "Sunscreen",
  "Surfboards",
  "Swimming",
  "Swimwear",
  "Tablets/iPads",
  "Tight clothing",
  "Touching the exhibits",
  "Touching marine life",
  "Touching animals",
  "Touching plants",
  "Tripods",
  "Umbrellas",
  "Unaccompanied minors",
  "Visible tattoos",
  "Valuables",
  "Vaping",
  "Video recording",
  "Walking frames",
  "Walking sticks",
  "Weapons or sharp objects",
  "Wearing a costume",
  "What is the pet policy? (optional)",
  "Pet-friendly"
];

export const mustCarryOptions = [
  "Beachwear",
  "Binoculars",
  "Biodegradable sunscreen",
  "Biodegradable insect repellent",
  "Boating licence",
  "Camera",
  "Cash",
  "Change of clothes",
  "Charged Smartphone",
  "Child safety seat",
  "Climbing gear",
  "Closed-toe shoes",
  "Clothes that can get dirty",
  "Collared shirt",
  "Comfortable clothes",
  "Comfortable shoes",
  "Cooking equipment",
  "Credit card",
  "Cycling clothing",
  "Daypack",
  "Deposit",
  "Disability card",
  "Dive log",
  "Diving certification",
  "Downloaded app",
  "Drinks",
  "Driver's license",
  "Face mask or protective covering",
  "FFP2 mask",
  "First aid kit",
  "Fishing license",
  "Flashlight",
  "Flip-flops",
  "Food",
  "Food and drinks",
  "Game box",
  "Garbage bag",
  "Gloves",
  "Goggles",
  "Trekking gear",
  "GPS/map",
  "Hair tie",
  "Hand sanitizer or tissues",
  "Hat",
  "Head covering or kippah",
  "Headphones",
  "Headscarf",
  "Helmet",
  "Hiking pants",
  "Hiking shoes",
  "Ingredients",
  "Insect repellent",
  "International driver's license",
  "Internet access",
  "Jacket",
  "Breathable clothing",
  "Long pants",
  "Long-sleeved shirt",
  "Medical mask",
  "Medical statement",
  "Motion sickness prevention",
  "Outdoor clothing",
  "Pacemaker card",
  "Packed lunch",
  "Passport",
  "Passport, copy accepted",
  "Passport or ID card",
  "Passport or ID card for children",
  "Passport or ID card, copy accepted",
  "Passport-sized photo",
  "Pen",
  "Personal medication",
  "Pillow",
  "Power bank",
  "Public transport ticket",
  "Quick-dry clothing",
  "Rain gear",
  "Reusable water bottle",
  "Sandals",
  "Sarong",
  "Scarf",
  "Shorts",
  "Signed waiver",
  "Sleeping bag",
  "Snacks",
  "Snorkeling gear",
  "Snow clothing",
  "Socks",
  "Sports shoes",
  "Sportswear",
  "Storage device",
  "Student card",
  "Sunglasses",
  "Sun hat",
  "Sunscreen",
  "Swimming cap",
  "Swimwear",
  "Tent",
  "Thermal clothing",
  "Tie",
  "Toiletries",
  "Towel",
  "Travel insurance",
  "Tripod",
  "T-shirt",
  "Umbrella",
  "ID card, copy accepted",
  "Visa, if required",
  "Warm clothing",
  "Warm shoes",
  "Water",
  "Waterproof bag",
  "Waterproof camera",
  "Waterproof shoes",
  "Water shoes",
  "Weather-appropriate clothing",
  "Wetsuit",
  "Windbreaker",
  "Winter sports gear",
  "Your own vehicle"
];
